spring.datasource.url=jdbc:postgresql://localhost:5432/todolistdb
spring.datasource.username=guilherme
spring.datasource.password=banco123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect